version: '3.8'

services:
  # hardhat-node:
  #   build: .
  #   container_name: hardhat-node
  #   ports:
  #     - "8545:8545"
  zookeeper:
    image: bitnami/zookeeper:3.9.2
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.8.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:14.6-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: yangguang
    volumes:
      - pgdata:/var/lib/postgresql/data

  express:
    build: ./server
    container_name: express
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: postgres://postgres:123456@postgres:5432/yangguang
 
volumes:
  pgdata:
