[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc-version = "0.8.21"  # Ensure the same version
optimizer = true  # Enable optimizer
optimizer-runs = 200  # Match Hardhat settings
nat-spec = false  